### ISSUE TITLE
Disabling validation

### ISSUE THREAD

**Issue by lonix1** [haacked/aspnet-client-validation#100]
For diagnostic and/or testing purposes we needed to disable the library once it's already loaded.

I tried this:
```js
v.remove(v.options.root)
```
And this:
```js
document.querySelectorAll('.my-form input:not([type="hidden"])').forEach(x => v.removeInput(x));
```
Both complete without error, but when I then interact with the form, and validation is expected to run, I get this console error:
```
Uncaught TypeError: i is not a function
  a http://localhost:5000/lib/aspnet-client-validation/dist/aspnet-validation.min.js:1
  setTimeout handler*i http://localhost:5000/lib/aspnet-client-validation/dist/aspnet-validation.min.js:1
  addInput http://localhost:5000/lib/aspnet-client-validation/dist/aspnet-validation.min.js:1
  scanInputs http://localhost:5000/lib/aspnet-client-validation/dist/aspnet-validation.min.js:1
  scan http://localhost:5000/lib/aspnet-client-validation/dist/aspnet-validation.min.js:1
  a http://localhost:5000/lib/aspnet-client-validation/dist/aspnet-validation.min.js:1
  bootstrap http://localhost:5000/lib/aspnet-client-validation/dist/aspnet-validation.min.js:1
  <anonymous> http://localhost:5000/signin:355
```

Are [`remove`](https://github.com/haacked/aspnet-client-validation/blob/5008fe31af9c0e78d655d76c64e98ac21e2805d5/dist/aspnet-validation.js#L1313) and [`removeInput`](https://github.com/haacked/aspnet-client-validation/blob/5008fe31af9c0e78d655d76c64e98ac21e2805d5/dist/aspnet-validation.js#L1038) intended to be usable by callers (in which case have I made a mistake in how I'm using them)? If not, is there some other way to disable the library once it's loaded, or is that impossible (and the only option is not to run it in the first place)?

**Comment by dahlbyk** [comment]
> Are [`remove`](https://github.com/haacked/aspnet-client-validation/blob/5008fe31af9c0e78d655d76c64e98ac21e2805d5/dist/aspnet-validation.js#L1313) and [`removeInput`](https://github.com/haacked/aspnet-client-validation/blob/5008fe31af9c0e78d655d76c64e98ac21e2805d5/dist/aspnet-validation.js#L1038) intended to be usable by callers?

I'd say yes.

> in which case have I made a mistake in how I'm using them

I don't think so. `remove()` just hasn't been thoroughly tested.

------------------

I'm pretty sure `i is not a function` is because we don't check if `validate` exists here, which is easy to fix:
https://github.com/haacked/aspnet-client-validation/blob/5008fe31af9c0e78d655d76c64e98ac21e2805d5/src/index.ts#L1030-L1034

Better would be to actually remove that callback (trickier because we need to keep track of which event type it's listening to):
https://github.com/haacked/aspnet-client-validation/blob/5008fe31af9c0e78d655d76c64e98ac21e2805d5/src/index.ts#L1042-L1049

We could also remove the form event listeners for forms without any remaining inputs:
https://github.com/haacked/aspnet-client-validation/blob/5008fe31af9c0e78d655d76c64e98ac21e2805d5/src/index.ts#L969-L970

Would you also expect existing validation messages/summaries to be cleared? Or just leave them and allow submitting the form, as would be the normal experience with server-only validation?

**Comment by dahlbyk** [comment]
> it's reasonable to expect that it would be "reset" to it's original state, i.e. no existing messages/summaries.

But its original state might have been server-side errors. 🤔

I think most straightforward would be for `remove()` to _not_ reset validation messages, but also add a public method to explicitly `removeMessages()` that would clear all summaries and individual messages. If you want a full reset you would:
```ts
v.removeMessages();
v.remove();
```

(IMO a small but useful change to allow `scan()`, `remove()`, etc to be called without `root`, defaulting to `this.options.root`.)

**Comment by dahlbyk** [comment]
I've started working on this. Will open a PR soon.

**Comment by dahlbyk** [comment]
"soon" https://github.com/haacked/aspnet-client-validation/pull/110
