### ISSUE TITLE
Initial isFieldValid returns true when field is empty and uses required validator.

### ISSUE THREAD

**Issue by RyanONeill1970** [haacked/aspnet-client-validation#108]
On calling v.isFieldValid and passing an element it appears to use the cached version even though it has not previously run.

From the code for isFieldValid I can see the validation is set up to run on the debounce timeout, which I have set to 0 on bootstrap.

This results in isFieldValid returning true even though it has not called the validator. The validator fires after the function returns and evaluates to false. There is no async code.

I'm going to work around this by using the callback.

Is it an error that the state is returned as true when it has not been through a validator? From the docs on this function it's not obvious that the return state is cached.

Would you consider an alternative (which I'll help with) if the debounce is 0, calling the validator and returning the state immediately?
That might still make the return value unreliable if debounce is not 0 though.

Basic idea of what I am doing is below;

`<input type="text" data-val="true" data-val-required="Please enter."id="ElementX" name="ElementX" value="" />
`
```
// Bootstrap was set with v.debounce = 0;

// On a button click, check if empty field is valid.
let isValid = v.isFieldValid(element));

// Returns true

```

Thank you

Ryan

**Comment by dahlbyk** [comment]
You're absolutely correct that the debounce is making an otherwise synchronous validation async so it immediately returns `true`. We should fix that.

It's worth mentioning here that returning the cached value is what happens "by design" if there's a remote or other Promise-returning validator involved. Ideally the method would return a `Promise<bool>`, but that's a breaking change. Maybe v2?

> That might still make the return value unreliable if debounce is not 0 though.

This is also correct, and we should fix that.

1. `validateField()` should always call the underlying validator, undebounced.
2. Only the `change`/`input` handler should be debounced.

I actually have a branch in progress (for #100) that's adjusting how the callback is wired/unwired, so I can include this fix in that change.

**Comment by RyanONeill1970** [comment]
Well, thank you very much. Sorry to pile stuff on to your plate.

**Comment by dahlbyk** [comment]
Give this a try? https://github.com/haacked/aspnet-client-validation/pull/110

**Comment by RyanONeill1970** [comment]
Not sure if Phil has made his changes from review. Let me know when the review is good to test.

**Comment by dahlbyk** [comment]
I fixed the bug Phil found. 👍  Please test!
