### ISSUE TITLE
isFieldValid unexpected behaviours

### ISSUE THREAD

**Issue by FuriousOrange** [haacked/aspnet-client-validation#28]
Hi,

I've got a use case for needing to validate a single field before sending some info to a rest api when clicking a button. It seems like isFieldValid should do this. However I'm having some issues with the way it works. If I provide the true argument to pre-validate the form it will then validate all other inputs on the form and show their error messages. This feels like a bad user experience as the user may not have got round to entering those fields yet.

Another issue is when you supply the prevalidate false argument then isFieldValid is assuming that some user interaction has happened and that there is an error message in the element cache for the form. I've made a fiddle that hopefully illustrates the issue.

https://jsfiddle.net/po75dqef/1/

**Comment by dsbegnoche** [comment]
Ran into the 2nd issue as well, where `isFieldValid` is returning incorrectly.  I believe it to be due to this check
https://github.com/haacked/aspnet-client-validation/blob/44e008b966caeb6066ae2300ddaad7d4b94d023a/src/index.ts#LL700C23-L700C23

If I am understanding the expectation correctly, updating that line to `return this.summary[fieldUID] == null;` would address the issue.
